---
version: 2

references:
  import_check_root: &import_check_root
    /home/circleci/import-check

  yarn_cache_key: &yarn_cache_key
    v1-yarn-{{ checksum "yarn.lock" }}

  build_config: &build_config
    docker:
      - image: circleci/node:10.12.0
    working_directory: *import_check_root

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *import_check_root

jobs:
  create_workspace:
    <<: *build_config
    steps:
      - checkout
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: *yarn_cache_key
          paths:
            - node_modules
      - persist_to_workspace:
          root: *import_check_root
          paths:
            - .
  test:
    <<: *build_config
    steps:
      - *attach_workspace
      - run: yarn test
      - run: npx nyc report --reporter=lcov | npx codecov

  danger_comments:
    <<: *build_config
    steps:
      - *attach_workspace
      - run:
          name: Danger Comments
          command: yarn danger ci

workflows:

  version: 2

  build:
    jobs:
      - create_workspace:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - create_workspace
  test_pull_request:
    jobs:
      - create_workspace
      - test:
          requires:
            - create_workspace
      - danger_comments:
          requires:
            - create_workspace
